version: '3'
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - app_network

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app_network

  frontend:
    build:
      context: ./sys-stats
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
